apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
- deployment.yaml
- rbac.yaml
commonLabels:
  app: gatekeeper-exporter
images:
- name: quay.io/xenitab/gatekeeper-exporter
  newTag: a00ac824
