apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gatekeeper-exporter
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gatekeeper-exporter
subjects:
- kind: ServiceAccount
  name: gatekeeper-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gatekeeper-exporter
